{{- if and (or (.Files.Glob "files/docker-entrypoint-initdb.d/*.sh") .Values.initdbScripts) (not .Values.initdbScriptsConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}-init-scripts
  labels: {{- include "elasticsearch.labels" . | nindent 4 }}
    component: master
data:
{{- if and (.Files.Glob "files/docker-entrypoint-initdb.d/*.sh") (not .Values.initdbScriptsConfigMap) }}
{{ (.Files.Glob "files/docker-entrypoint-initdb.d/*.sh").AsConfig | indent 2 }}
{{- end }}
{{- with .Values.initdbScripts }}
{{ toYaml . | indent 2 }}
{{- end }}
{{ end }}
